// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC44RXyUrhUxnISClAUL5CzCqXIMDfuEuY',
    appId: '1:381561541061:web:a3ee1c86fe5b928035bbac',
    messagingSenderId: '381561541061',
    projectId: 'bus-tracking-app-715be',
    authDomain: 'bus-tracking-app-715be.firebaseapp.com',
    storageBucket: 'bus-tracking-app-715be.firebasestorage.app',
    measurementId: 'G-PV7658HFDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPrXV81gAV_CMemaM8PLXRgTSysLnfSkQ',
    appId: '1:381561541061:android:795224735624f62c35bbac',
    messagingSenderId: '381561541061',
    projectId: 'bus-tracking-app-715be',
    storageBucket: 'bus-tracking-app-715be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeMnnCB5cj91kB1uaZGQBUU1NXmuXBSXw',
    appId: '1:381561541061:ios:26d83feb8d39b82235bbac',
    messagingSenderId: '381561541061',
    projectId: 'bus-tracking-app-715be',
    storageBucket: 'bus-tracking-app-715be.firebasestorage.app',
    authDomain: 'bus-tracking-app-715be.firebaseapp.com',
    iosClientId: '381561541061-m63o8srnncd0flmgqot6o3u4c0b88dnm.apps.googleusercontent.com',
    iosBundleId: 'mobile.catchybus.catchybus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeMnnCB5cj91kB1uaZGQBUU1NXmuXBSXw',
    appId: '1:381561541061:ios:26d83feb8d39b82235bbac',
    messagingSenderId: '381561541061',
    projectId: 'bus-tracking-app-715be',
    storageBucket: 'bus-tracking-app-715be.firebasestorage.app',
    iosClientId: '381561541061-m63o8srnncd0flmgqot6o3u4c0b88dnm.apps.googleusercontent.com',
    iosBundleId: 'mobile.catchybus.catchybus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKZjpVT5EnyKlmc1CrJA88Rm-hNKk1ISA',
    appId: '1:381561541061:web:0002210a851c70bc35bbac',
    messagingSenderId: '381561541061',
    projectId: 'bus-tracking-app-715be',
    authDomain: 'bus-tracking-app-715be.firebaseapp.com',
    storageBucket: 'bus-tracking-app-715be.firebasestorage.app',
    measurementId: 'G-T3ZXRQMSXQ',
  );
}
